### ISSUE TITLE
笔做的相当好！！！

### ISSUE THREAD

**Issue by caolong928** [freshtech2021/ChanlunX#1]
笔做得相当好，是我见过做得最好的了！！我只用画笔的公式，非常感谢，这下换软件也不怕了，看了很多公式都不太满意，本来想自己编的，身体太差，没精力了，在这儿能找到，真是运气。再次感谢！段的理解有问题，所以画得不对，段破坏才产生新段，这个对于操作非常重要，这个缠师65到67课上有。

**Comment by kldcty** [comment]
可以切换画段模式，你可能没有用对模式。
欢迎来群里交流。

**Comment by gxs-gc** [comment]
厉害了
